# Generated by Django 5.1.6 on 2025-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Картинка услуги'),
        ),
    ]
