# Generated by Django 5.1.6 on 2025-06-08 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_service_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-booking__created_at'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['full_name'], 'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(blank=True, verbose_name='Что входит в услугу'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'service', 'date', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'specialist')},
        ),
        migrations.AlterUniqueTogether(
            name='specialist',
            unique_together={('user', 'full_name')},
        ),
    ]
